require 'vagrant-openstack-provider'
Vagrant.configure('2') do |config |
	config.ssh.username = 'ubuntu'
	config.ssh.private_key_path = "C:\\Users\\Admin\\vagrant\\regishumana.pem"
	config.vm.provider :openstack do|os, override |
		os.identity_api_version = '3'
		os.openstack_auth_url = 'http://10.28.3.240:5000/v3'
		os.domain_name = 'fundacion-jala'
		os.username = 'regishumana'
		os.password = 'j9390557H'
		os.tenant_name = '2099bc1dc3ec4c76a9cdbab47ea675a7'
		os.project_name = 'fj_at09'
		os.keypair_name = 'regishumana'
		os.image = 'ubuntu-16.04-amd64-server_20190215'
		os.flavor = 'student.2.2R'
		os.server_name = 'rhumana-test1-01'
		override.vm.synced_folder '.', '/vagrant', disabled: true
	end
end